require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/SubjectStub:
  Enabled: false
