version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - ruby/install-deps:
          clean-bundle: true
      - ruby/rubocop-check
      - ruby/rspec-test:
          rerun-fail: false
